‚óè FlaskApp.service - My Flask Website
   Loaded: loaded (/etc/systemd/system/FlaskApp.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-01-02 15:35:15 EST; 26s ago
  Process: 11405 ExecStart=/home/webmaster/web/FlaskApp/FlaskApp/venv/bin/gunicorn --workers 3 --bind unix:FlaskApp.sock -m 007 __init__:app (code=exited, status=1/FAILURE)
 Main PID: 11405 (code=exited, status=1/FAILURE)

Jan 02 15:35:15 server gunicorn[11405]:   File "/home/webmaster/web/FlaskApp/FlaskApp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
Jan 02 15:35:15 server gunicorn[11405]:     time.sleep(0.1)
Jan 02 15:35:15 server gunicorn[11405]:   File "/home/webmaster/web/FlaskApp/FlaskApp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
Jan 02 15:35:15 server gunicorn[11405]:     self.reap_workers()
Jan 02 15:35:15 server gunicorn[11405]:   File "/home/webmaster/web/FlaskApp/FlaskApp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
Jan 02 15:35:15 server gunicorn[11405]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jan 02 15:35:15 server gunicorn[11405]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Jan 02 15:35:15 server systemd[1]: FlaskApp.service: Main process exited, code=exited, status=1/FAILURE
Jan 02 15:35:15 server systemd[1]: FlaskApp.service: Unit entered failed state.
Jan 02 15:35:15 server systemd[1]: FlaskApp.service: Failed with result 'exit-code'.
